server:
  port: 1136
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 150.158.50.9
    # Redis服务器连接端口
    port: 7738
    # Redis服务器连接密码（默认为空）
    password: zgL5Afi0UVasbxHm{}:Unx@#*94d
    # 连接超时时间
    timeout: 2s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
